squashed commits
negetion trial

add UNIT_SPACE

trial

added rules + typo fix

new rule trial

added new category ind isabled list

disabled a new category

typo update + action file rules added

typo fix

typo

lang fix typos

lang tool fix

misspell typo correction

mispell typo corrections

trial disabling rule

change action v3

revert

reporter changed to pr check

runn on failure

merging into 1

rules changed for testing

run

a12b

test1

update1

revert

change 0.12

merged different processes into 1

change

punctuations

v2

removed success clause

fix

individual jobs

update rules

1

rrevert

added new rule

added pattern into lang tool

v1

pattern restrictions lifted

flags=1

added flags

added if statement

spellcheck yaml added

swapped tools

added if failure on lang tool

added run on failure

added language tool in release.yml

added misspell in release

disabled categories added

langtool

reporter level

reporter level changed

misspell

reviewdog misspell add

env reviewdog

lang tool

reporter level change

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,14 +26,6 @@ jobs:
         with:
           go-version-file: magefiles/go.mod
 
-      - name: Validate release version
-        uses: magefile/mage-action@v2
-        with:
-          version: latest
-          args: "sync:validateRelease"
-        env:
-          BOTKUBE_RELEASE_VERSION: "${{ inputs.version }}.0"
-
       - name: install npm
         run: |
           npm install
@@ -42,33 +34,32 @@ jobs:
         run: |
           npm run prettier:fix
 
-      - name: Running misspell check
+      - name: Running Language tool
+        uses: reviewdog/action-languagetool@v1
+        with:
+          github_token: ${{ secrets.github_token }}
+           # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
+          reporter: github-check
+          # Change reporter level if you need.
+          level: info
+          language: en-US
+          disabled_categories: 'TYPOS,TYPOGRAPHY,CASING'
+            
+
+      - name: running misspell
+      # to run even after lang tool failure
+        if: success() || failure()
         uses: reviewdog/action-misspell@v1
-        with: 
-          # github_token:  ${{ secrets.GH_TOKEN }}
-          pattern: "**.md"
-          level: error
+        with:
+          github_token: ${{ secrets.github_token }}
           locale: "US"
+          reporter: github-check
           exclude: |
             ./.git/*
             ./.cache/*
 
-      - name: Run LanguageTool
-        uses: reviewdog/action-languagetool@v1
-        with:
-          github_token: ${{ secrets.GH_TOKEN }}
-          reporter: github-pr-review
-          level: error
-          patterns: "**/*.md **/*.txt"
-          custom_api_endpoint: ''
-          ### Flags for LanguageTool ###
-          # Ref: https://languagetool.org/http-api/swagger-ui/#!/default/post_check
-          language: 'en-US'
-          enabled_rules: ''
-          disabled_rules: 'WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,CURRENCY,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END,METRIC_UNITS_EN_US,ENGLISH_WORD_REPEAT_BEGINNING_RULE,DOUBLE_PUNCTUATION'
-          enabled_categories: ''
-          disabled_categories: 'TYPOS,TYPOGRAPHY,CASING'
-          enabled_only: 'false'
+
+
 
 
 
